[window]
opacity = 0.7
padding = { x = 0, y = 0 }

[font]
normal = { family = "JetBrains Mono Medium", style = "Medium" }
bold = { family = "JetBrains Mono Medium", style = "Medium" }

[keyboard]
bindings = [
    { key = "Return", mods = "Control", action = "SpawnNewInstance" },
    { key = "j", mods = "Control", action = "ToggleViMode" },
    { key = "e",  mods = "Control", chars = "ehlo" }
]

[colors.primary]
foreground = "0xe3e3e3"
bright_foreground = "0xffffff"
dim_foreground = "0xe3e3e3"
background = "0x1f1f1f"

[colors.cursor]
text = "0x191622"
cursor = "0xf8f8f2"

[colors.search]
matches = { foreground = "0xb2b2b2", background = "0xb26818" }
focused_match = { foreground = "CellBackground", background = "CellForeground" }

[colors.normal]
black = "0x000000"
red = "0xb21818"
green = "0x18b218"
yellow = "0xb26818"
blue = "0x174396"
magenta = "0xb218b2"
cyan = "0x18b2b2"
white = "0xb2b2b2"

[colors.bright]
black = "0x686868"
red = "0xff5454"
green = "0x54ff54"
yellow = "0xffff54"
blue = "0x5454ff"
magenta = "0xff54ff"
cyan = "0x54ffff"
white = "0xffffff"

[colors.dim]
black = "0x000000"
red = "0xb21818"
green = "0x18b218"
yellow = "0xb26818"
blue = "0x1818b2"
magenta = "0xb218b2"
cyan = "0x18b2b2"
white = "0xb2b2b2"
