[window]
dynamic_title = true
dynamic_padding = true
decorations = 'None'


[font]
normal = { family = "Terminus", style = "Regular" }
bold = { family = "Terminus", style = "Bold" }
italic = {family = "Terminus", style = "italic"}

[keyboard]
bindings = [
    { key = "Return", mods = "Control", action = "SpawnNewInstance" },
]

[general]
import = [
    '~/.config/alacritty/colors.d/nord.toml'
    # '~/.config/alacritty/colors.d/nordic.toml'
    # '~/.config/alacritty/colors.d/default.toml'
]
