# Wallpaper setup

preload = /usr/share/backgrounds/active/pexels-sewws-2670898.jpg
preload = /usr/share/backgrounds/active/pexels-fabiano-rodrigues-794857-1662298.jpg

wallpaper = monitor1,/usr/share/backgrounds/active/pexels-sewws-2670898.jpg
wallpaper = monitor2,/usr/share/backgrounds/active/pexels-fabiano-rodrigues-794857-1662298.jpg
